### ISSUE TITLE
Port to GTK+ 3

### ISSUE THREAD

**Issue by yell0wfl4sh** [sugarlabs/read-sd-comics#5]

**Comment by tonadev** [comment]
This issue must be closed as it was solved at #6. And delete Port to GTK3 - Read-sd-comics-activity  task at Google Code-In.
Also delete Port to GTK3 - diccionario-guarani-castellano-activity task at Google Code-In as there is no issue nor need to Port to GTK3 (it already use Gtk3)

*(CGI) PS: I didn't pay attention to this and claimed the task, what should I do now?*

**Comment by rhl-bthr** [comment]
Thanks for notifying.

**Comment by quozl** [comment]
_@tonadev, for GCI procedural problems, speak with [a mentor](https://wiki.sugarlabs.org/go/Google_Code_In_2018#Mentors) or the organisation co-administrators @chimosky or @walterbender._
